import type { Metadata } from "next";
import { ArrowDown, ArrowUpRight, Check, Heart, Lock, Sparkles } from "lucide-react";
import { PixCheckout } from "@/components/PixCheckout";
import { brl, CATALOG } from "@/lib/catalog";

export const metadata: Metadata = {
  title: "Seu jeito de amar, pelos seus números | DestinyVox",
  description: "Entenda seu jeito de se relacionar com um mapa numerológico por R$ 19,90. Adicione sua primeira sinastria e explore o encontro entre dois mapas.",
};
const benefits = [
  ["01", "O que você busca", "Às vezes, o pedido é carinho. A necessidade é ser ouvido.", "O Desejo da Alma abre uma leitura sobre o que importa por dentro. Um ponto de partida para dar nome ao que você espera de um vínculo.", "Desejo da Alma · vogais do seu nome"],
  ["02", "O que você demonstra", "O que você sente nem sempre é o que chega ao outro.", "Expressão e Personalidade colocam lado a lado seu modo de agir e a presença que você transmite. Observe onde sua intenção pode pedir palavras mais claras.", "Expressão + Personalidade · letras do seu nome"],
  ["03", "O espaço de cada um", "Como construir um nós sem se perder de si?", "Caminho de Vida e Maturidade convidam você a olhar para escolhas, autonomia e projetos. Conhecer seus próprios temas ajuda a conversar sobre os planos a dois.", "Caminho de Vida + Maturidade · nome e nascimento"],
  ["04", "O momento que você vive", "Duas pessoas podem estar em ritmos diferentes.", "Seus ciclos de ano, mês e dia oferecem temas para observar a fase atual. Use essa leitura para escolher o que merece atenção na sua rotina e nas suas relações.", "Ano, Mês e Dia Pessoal · ciclos do calendário"],
];
const faqs = [
  ["Estou comprando meu mapa ou uma sinastria?", "A compra principal é o seu mapa numerológico completo por R$ 19,90, com nove números e uma seção sobre relacionamentos. A primeira sinastria é um adicional opcional de R$ 9,90, já selecionado nesta página. Com ele, o total é R$ 29,80. Você pode desmarcá-lo para comprar apenas o mapa por R$ 19,90."],
  ["Preciso dos dados da outra pessoa agora?", "Sim, se quiser receber a sinastria pronta. Informe o nome completo de nascimento e a data do seu crush no próprio adicional. Não pedimos o e-mail dessa pessoa. Se não tiver os dados agora, desmarque o adicional e compre apenas o mapa."],
  ["Como recebo minha primeira sinastria?", "Após a confirmação do Pix, geramos seu mapa e a comparação completa com o crush informado no checkout. Ao abrir seu produto, a sinastria já estará pronta na seção Relacionamentos. Ela fica salva para reler sem novo pagamento."],
  ["E se eu quiser comparar com outras pessoas?", "Você pode cadastrar outras pessoas gratuitamente. Cada nova comparação custa R$ 14,90 e usa um crédito vinculado ao seu mapa. Não há assinatura. Sem o adicional inicial, você também pode comprar sua primeira comparação por esse valor dentro do produto."],
  ["A sinastria diz se vamos dar certo?", "Ela organiza uma leitura simbólica dos dois mapas para explorar afinidades, diferenças e formas de conversar. Não dá uma nota ao casal nem decide sobre o futuro da relação. A proposta é trazer perguntas melhores para a vida real."],
  ["Serve para quem está solteiro?", "Sim. A leitura individual já explora suas necessidades e sua forma de se relacionar. A sinastria é opcional: você pode escolher alguém para comparar depois, quando fizer sentido."],
];

export default function SynastryPage() {
  return <div className="map-theme min-h-screen">
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-4 border-b border-black/20 px-5 py-6 sm:px-10"><a href="/" className="map-eyebrow flex items-center gap-2"><span className="text-2xl">✳</span> DestinyVox</a><a href="/acesso" className="text-xs underline underline-offset-4">Já tenho meu mapa <ArrowUpRight className="ml-1 inline size-3" /></a></header>
    <main>
      <section data-analytics-section="hero" className="mx-auto grid max-w-7xl gap-12 px-5 pb-12 pt-12 sm:px-10 sm:py-20 lg:grid-cols-[1.2fr_1fr] lg:gap-16">
        <div><p className="map-eyebrow text-[#875f54]">Autoconhecimento que encontra o amor</p><h1 className="mt-6 max-w-2xl font-editorial text-[44px] leading-[1.06] tracking-tight sm:text-6xl lg:text-7xl">O que seus números dizem sobre<br /><em className="font-normal text-[#875f54]">seu jeito de amar?</em></h1><p className="mt-7 max-w-lg text-base leading-8 text-muted-foreground">Você quer proximidade. A outra pessoa pede espaço. Antes de tentar entender esse encontro, descubra o que você leva para ele.</p><p className="mt-4 max-w-lg text-sm leading-7 text-muted-foreground">Seu nome e nascimento viram um mapa de nove números: uma leitura sobre suas necessidades, sua expressão e seu momento de vida — com um espaço para explorar seus relacionamentos.</p><a data-analytics-id="cta-hero" href="#seu-mapa" className="mt-8 inline-flex min-h-14 items-center justify-center gap-4 rounded-sm bg-[#79564c] px-6 py-4 text-sm text-white hover:bg-[#63453d]">Quero descobrir meu jeito de amar <ArrowDown className="size-4" /></a><p className="mt-4 text-xs leading-6 text-muted-foreground">Mapa completo por {brl(CATALOG.map.price)} · Pix · Pagamento único</p></div>
        <div className="relative self-center border border-black/20 bg-[#ede7df] p-6 sm:p-9">
          <p className="map-eyebrow text-[#875f54]">Duas histórias. Um encontro.</p>
          <div className="relative mx-auto my-10 flex h-52 max-w-80 items-center justify-center" aria-hidden="true"><div className="absolute left-[2%] flex size-44 items-center justify-center rounded-full border border-[#875f54]/50 bg-[#e1d1c5]/40"><span className="-translate-x-5 -translate-y-1 font-editorial text-7xl text-[#79564c]">2</span></div><div className="absolute right-[2%] flex size-44 items-center justify-center rounded-full border border-[#626b51]/50 bg-[#d8decf]/30"><span className="translate-x-5 -translate-y-1 font-editorial text-7xl text-[#626b51]">7</span></div><span className="z-10 flex size-9 items-center justify-center rounded-full bg-[#f4f2eb]"><Heart className="size-4 text-[#875f54]" /></span></div>
          <div className="border-t border-black/20 pt-5"><p className="font-editorial text-2xl">Proximidade encontra profundidade.</p><p className="mt-3 text-sm leading-7 text-muted-foreground">Um busca troca. O outro precisa de tempo para elaborar. Como combinar presença e espaço sem transformar a diferença em distância?</p><p className="map-eyebrow mt-5 text-[9px] text-[#875f54]">Exemplo ilustrativo de sinastria · adicional opcional</p></div>
        </div>
      </section>
      <div className="border-y border-black/20"><div className="mx-auto grid max-w-7xl gap-4 px-5 py-5 text-xs sm:grid-cols-3 sm:px-10"><p><Sparkles className="mr-2 inline size-4 text-[#875f54]" />Nove números interpretados</p><p><Heart className="mr-2 inline size-4 text-[#875f54]" />Uma leitura sobre seus vínculos</p><p><Lock className="mr-2 inline size-4 text-[#875f54]" />Seu espaço privado de leitura</p></div></div>
      <section data-analytics-section="leitura" className="mx-auto max-w-7xl px-5 py-14 sm:px-10 sm:py-20"><p className="map-eyebrow text-[#875f54]">Primeiro, um olhar para você</p><h2 className="mt-4 max-w-2xl font-editorial text-4xl leading-tight sm:text-5xl">Entender seus vínculos<br />começa por se reconhecer.</h2><div className="mt-10 grid border-l border-t border-black/20 md:grid-cols-2">{benefits.map(([index, label, title, text, calculation]) => <article data-analytics-section={`beneficio-${index}`} key={index} className="border-b border-r border-black/20 p-6 sm:p-8"><p className="map-eyebrow text-[#875f54]">{index} / {label}</p><h3 className="mt-5 max-w-md font-editorial text-3xl leading-tight">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{text}</p><p className="map-eyebrow mt-6 border-t border-black/10 pt-4 text-[9px]">{calculation}</p></article>)}</div></section>
      <section data-analytics-section="como-funciona" className="bg-[#79564c] text-[#f6f1eb]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-10 sm:py-16 lg:grid-cols-2"><div><p className="map-eyebrow text-[#e4cfc3]">Depois, um olhar para o encontro</p><h2 className="mt-5 font-editorial text-4xl leading-tight sm:text-5xl">E se vocês colocassem<br />os dois mapas em diálogo?</h2><p className="mt-6 max-w-lg text-sm leading-7 text-[#eee1d7]">Com o adicional de sinastria, você recebe uma comparação completa entre o seu mapa e o do seu crush em cinco dimensões da relação. Cada uma traz os números dos dois, pontos de encontro, diferenças que merecem conversa e um exercício para experimentar juntos.</p><p className="mt-6 text-sm">Sua primeira comparação: + {brl(CATALOG.synastry.price)} no checkout.</p></div><ol className="space-y-6">{[["Comece com seus dados", "Informe seu nome, nascimento e e-mail para preparar seu mapa numerológico."], ["Inclua os dados do crush", "A primeira sinastria já está selecionada por + R$ 9,90. Preencha o nome completo e o nascimento da outra pessoa no adicional. Se preferir só o mapa, basta desmarcar."], ["Receba os dois prontos", "Após o Pix, seu mapa e a sinastria chegam no mesmo acesso. A comparação fica salva para reler; novas sinastrias custam R$ 14,90 cada."]].map(([title, text], i) => <li className="flex gap-5 border-b border-white/20 pb-6 last:border-0" key={title}><span className="font-editorial text-3xl text-[#e4cfc3]">0{i + 1}</span><div><h3 className="font-medium">{title}</h3><p className="mt-2 text-sm leading-7 text-[#eee1d7]">{text}</p></div></li>)}</ol></div></section>
      <section data-analytics-section="seu-mapa" id="seu-mapa" className="mx-auto grid max-w-7xl scroll-mt-5 gap-10 px-5 py-14 sm:px-10 sm:py-20 lg:grid-cols-[.9fr_1.1fr] lg:gap-16"><div><p className="map-eyebrow text-[#875f54]">Seu mapa. Suas descobertas.</p><h2 className="mt-4 font-editorial text-4xl leading-tight sm:text-5xl">Mais clareza sobre você.<br /><em className="font-normal text-[#875f54]">Mais assunto entre vocês.</em></h2><div className="mt-8 border-y border-black/20 py-6"><p className="map-eyebrow">Seu mapa numerológico completo</p><p className="mt-3 font-editorial text-5xl">{brl(CATALOG.map.price)}</p><p className="mt-2 text-xs text-muted-foreground">Pagamento único · adicionais opcionais</p><ul className="mt-6 space-y-4 text-sm">{["Nove números com interpretações e cálculos", "Seção sobre suas necessidades e seus vínculos", "Ciclos de ano, mês e dia na sua leitura", "Cadastro gratuito de outras pessoas", "Acesso privado no celular e no computador"].map(text => <li key={text} className="flex items-start gap-3"><Check className="size-4 shrink-0 text-[#875f54]" />{text}</li>)}</ul></div><div className="mt-6 border-l-2 border-[#875f54] pl-5"><p className="text-sm font-medium">Receba sua primeira sinastria pronta</p><p className="mt-2 text-sm leading-7 text-muted-foreground">O adicional de {brl(CATALOG.synastry.price)} já está selecionado no formulário e pode ser desmarcado. Mapa + primeira sinastria: <strong className="text-foreground">{brl(CATALOG.map.price + CATALOG.synastry.price)}</strong>. Preencha os dados do crush no adicional e receba a comparação pronta junto do mapa.</p></div></div><div className="min-w-0 rounded-sm border border-black/20 bg-[#eeece3] p-5 sm:p-8"><PixCheckout relationship /></div></section>
      <section data-analytics-section="faq" className="mx-auto grid max-w-7xl gap-8 border-t border-black/20 px-5 py-12 sm:px-10 sm:py-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="map-eyebrow text-[#875f54]">Antes de começar</p><h2 className="mt-4 font-editorial text-4xl">Vamos esclarecer?</h2></div><div>{faqs.map(([q, a], index) => <details data-analytics-id={`faq-${index + 1}`} key={q} className="border-b border-black/20 py-5 first:pt-0"><summary className="cursor-pointer text-sm font-medium leading-6">{q}</summary><p className="mt-4 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></section>
    </main><footer className="border-t border-black/20 px-5 py-8 text-center"><p className="map-eyebrow">✳ DestinyVox · Um olhar para você. Um espaço para o encontro.</p></footer>
  </div>;
}
